package com.multipleapp.clonespace;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;
/* loaded from: classes.dex */
public final class I9 {
    public int a;
    public final L9 b;
    public final K9 c;
    public final J9 d;
    public final M9 e;
    public HashMap f;

    /* JADX WARN: Type inference failed for: r0v0, types: [java.lang.Object, com.multipleapp.clonespace.L9] */
    /* JADX WARN: Type inference failed for: r0v1, types: [java.lang.Object, com.multipleapp.clonespace.K9] */
    /* JADX WARN: Type inference failed for: r0v2, types: [com.multipleapp.clonespace.J9, java.lang.Object] */
    /* JADX WARN: Type inference failed for: r0v3, types: [com.multipleapp.clonespace.M9, java.lang.Object] */
    public I9() {
        ?? obj = new Object();
        obj.a = 0;
        obj.b = 0;
        obj.c = 1.0f;
        obj.d = Float.NaN;
        this.b = obj;
        ?? obj2 = new Object();
        obj2.a = -1;
        obj2.b = 0;
        obj2.c = -1;
        obj2.d = Float.NaN;
        obj2.e = Float.NaN;
        obj2.f = Float.NaN;
        obj2.g = -1;
        obj2.h = null;
        obj2.i = -1;
        this.c = obj2;
        ?? obj3 = new Object();
        obj3.a = false;
        obj3.d = -1;
        obj3.e = -1;
        obj3.f = -1.0f;
        obj3.g = -1;
        obj3.h = -1;
        obj3.i = -1;
        obj3.j = -1;
        obj3.k = -1;
        obj3.l = -1;
        obj3.m = -1;
        obj3.n = -1;
        obj3.o = -1;
        obj3.p = -1;
        obj3.q = -1;
        obj3.r = -1;
        obj3.s = -1;
        obj3.t = -1;
        obj3.u = -1;
        obj3.v = 0.5f;
        obj3.w = 0.5f;
        obj3.x = null;
        obj3.y = -1;
        obj3.z = 0;
        obj3.A = 0.0f;
        obj3.B = -1;
        obj3.C = -1;
        obj3.D = -1;
        obj3.E = 0;
        obj3.F = 0;
        obj3.G = 0;
        obj3.H = 0;
        obj3.I = 0;
        obj3.J = 0;
        obj3.K = 0;
        obj3.L = Integer.MIN_VALUE;
        obj3.M = Integer.MIN_VALUE;
        obj3.N = Integer.MIN_VALUE;
        obj3.O = Integer.MIN_VALUE;
        obj3.P = Integer.MIN_VALUE;
        obj3.Q = Integer.MIN_VALUE;
        obj3.R = Integer.MIN_VALUE;
        obj3.S = -1.0f;
        obj3.T = -1.0f;
        obj3.U = 0;
        obj3.V = 0;
        obj3.W = 0;
        obj3.X = 0;
        obj3.Y = -1;
        obj3.Z = -1;
        obj3.a0 = -1;
        obj3.b0 = -1;
        obj3.c0 = 1.0f;
        obj3.d0 = 1.0f;
        obj3.e0 = -1;
        obj3.f0 = 0;
        obj3.g0 = -1;
        obj3.k0 = false;
        obj3.l0 = false;
        obj3.m0 = true;
        obj3.n0 = 0;
        this.d = obj3;
        ?? obj4 = new Object();
        obj4.a = 0.0f;
        obj4.b = 0.0f;
        obj4.c = 0.0f;
        obj4.d = 1.0f;
        obj4.e = 1.0f;
        obj4.f = Float.NaN;
        obj4.g = Float.NaN;
        obj4.h = -1;
        obj4.i = 0.0f;
        obj4.j = 0.0f;
        obj4.k = 0.0f;
        obj4.l = false;
        obj4.m = 0.0f;
        this.e = obj4;
        this.f = new HashMap();
    }

    public final void a(E9 e9) {
        J9 j9 = this.d;
        e9.d = j9.g;
        e9.e = j9.h;
        e9.f = j9.i;
        e9.g = j9.j;
        e9.h = j9.k;
        e9.i = j9.l;
        e9.j = j9.m;
        e9.k = j9.n;
        e9.l = j9.o;
        e9.m = j9.p;
        e9.n = j9.q;
        e9.r = j9.r;
        e9.s = j9.s;
        e9.t = j9.t;
        e9.u = j9.u;
        ((ViewGroup.MarginLayoutParams) e9).leftMargin = j9.E;
        ((ViewGroup.MarginLayoutParams) e9).rightMargin = j9.F;
        ((ViewGroup.MarginLayoutParams) e9).topMargin = j9.G;
        ((ViewGroup.MarginLayoutParams) e9).bottomMargin = j9.H;
        e9.z = j9.Q;
        e9.A = j9.P;
        e9.w = j9.M;
        e9.y = j9.O;
        e9.D = j9.v;
        e9.E = j9.w;
        e9.o = j9.y;
        e9.p = j9.z;
        e9.q = j9.A;
        e9.F = j9.x;
        e9.S = j9.B;
        e9.T = j9.C;
        e9.H = j9.S;
        e9.G = j9.T;
        e9.J = j9.V;
        e9.I = j9.U;
        e9.V = j9.k0;
        e9.W = j9.l0;
        e9.K = j9.W;
        e9.L = j9.X;
        e9.O = j9.Y;
        e9.P = j9.Z;
        e9.M = j9.a0;
        e9.N = j9.b0;
        e9.Q = j9.c0;
        e9.R = j9.d0;
        e9.U = j9.D;
        e9.c = j9.f;
        e9.a = j9.d;
        e9.b = j9.e;
        ((ViewGroup.MarginLayoutParams) e9).width = j9.b;
        ((ViewGroup.MarginLayoutParams) e9).height = j9.c;
        String str = j9.j0;
        if (str != null) {
            e9.X = str;
        }
        e9.Y = j9.n0;
        e9.setMarginStart(j9.J);
        e9.setMarginEnd(j9.I);
        e9.a();
    }

    public final Object clone() {
        I9 i9 = new I9();
        J9 j9 = i9.d;
        j9.getClass();
        J9 j92 = this.d;
        j9.a = j92.a;
        j9.b = j92.b;
        j9.c = j92.c;
        j9.d = j92.d;
        j9.e = j92.e;
        j9.f = j92.f;
        j9.g = j92.g;
        j9.h = j92.h;
        j9.i = j92.i;
        j9.j = j92.j;
        j9.k = j92.k;
        j9.l = j92.l;
        j9.m = j92.m;
        j9.n = j92.n;
        j9.o = j92.o;
        j9.p = j92.p;
        j9.q = j92.q;
        j9.r = j92.r;
        j9.s = j92.s;
        j9.t = j92.t;
        j9.u = j92.u;
        j9.v = j92.v;
        j9.w = j92.w;
        j9.x = j92.x;
        j9.y = j92.y;
        j9.z = j92.z;
        j9.A = j92.A;
        j9.B = j92.B;
        j9.C = j92.C;
        j9.D = j92.D;
        j9.E = j92.E;
        j9.F = j92.F;
        j9.G = j92.G;
        j9.H = j92.H;
        j9.I = j92.I;
        j9.J = j92.J;
        j9.K = j92.K;
        j9.L = j92.L;
        j9.M = j92.M;
        j9.N = j92.N;
        j9.O = j92.O;
        j9.P = j92.P;
        j9.Q = j92.Q;
        j9.R = j92.R;
        j9.S = j92.S;
        j9.T = j92.T;
        j9.U = j92.U;
        j9.V = j92.V;
        j9.W = j92.W;
        j9.X = j92.X;
        j9.Y = j92.Y;
        j9.Z = j92.Z;
        j9.a0 = j92.a0;
        j9.b0 = j92.b0;
        j9.c0 = j92.c0;
        j9.d0 = j92.d0;
        j9.e0 = j92.e0;
        j9.f0 = j92.f0;
        j9.g0 = j92.g0;
        j9.j0 = j92.j0;
        int[] iArr = j92.h0;
        if (iArr != null) {
            j9.h0 = Arrays.copyOf(iArr, iArr.length);
        } else {
            j9.h0 = null;
        }
        j9.i0 = j92.i0;
        j9.k0 = j92.k0;
        j9.l0 = j92.l0;
        j9.m0 = j92.m0;
        j9.n0 = j92.n0;
        K9 k9 = i9.c;
        k9.getClass();
        K9 k92 = this.c;
        k92.getClass();
        k9.a = k92.a;
        k9.c = k92.c;
        k9.e = k92.e;
        k9.d = k92.d;
        L9 l9 = i9.b;
        L9 l92 = this.b;
        l9.a = l92.a;
        l9.c = l92.c;
        l9.d = l92.d;
        l9.b = l92.b;
        M9 m9 = i9.e;
        m9.getClass();
        M9 m92 = this.e;
        m92.getClass();
        m9.a = m92.a;
        m9.b = m92.b;
        m9.c = m92.c;
        m9.d = m92.d;
        m9.e = m92.e;
        m9.f = m92.f;
        m9.g = m92.g;
        m9.h = m92.h;
        m9.i = m92.i;
        m9.j = m92.j;
        m9.k = m92.k;
        m9.l = m92.l;
        m9.m = m92.m;
        i9.a = this.a;
        return i9;
    }
}
